const optionsMockData = [
        {
          company: "RELIANCE",
          strikePrice : "3000",
          market_price: "₹20.40",
          oi: "16,939",
          expiry: "29 Feb '24",
          change: "0.30 (1.49%)",
          call_put: "Call",
        },
        {
          company: "HDFCBANK",
          strikePrice : "1450",
          market_price: "₹6.65",
          oi: "15,312",
          expiry: "29 Feb '24",
          change: "-2.40 (26.52%)",
          call_put: "Call",
        },
        {
          company: "SBIN",
          strikePrice : "770",
          market_price: "₹6.00",
          oi: "4,548",
          expiry: "29 Feb '24",
          change: "-4.55 (43.13%)",
          call_put: "Call",
        },
        {
          company: "ASTRAL",
          strikePrice : "2100",
          market_price: "₹32.85",
          oi: "1,633",
          expiry: "29 Feb '24",
          change: "29.10 (776.00%)",
          call_put: "Call",
        },
        {
          company: "ADANIENT",
          strikePrice : "3300",
          market_price: "₹48.20",
          oi: "1,481",
          expiry: "29 Feb '24",
          change: "1.85 (3.99%)",
          call_put: "Call",
        },
        {
          company: "M&M",
          strikePrice : "1840",
          market_price: "₹4.35",
          oi: "1,022",
          expiry: "29 Feb '24",
          change: "-4.40 (50.29%)",
          call_put: "Put",
        },
        {
          company: "TITAN",
          strikePrice : "3700",
          market_price: "₹37.95",
          oi: "3,138",
          expiry: "29 Feb '24",
          change: "11.05 (41.08%)",
          call_put: "Call",
        },
        {
          company: "TCS",
          strikePrice : "4100",
          market_price: "₹27.10",
          oi: "1,872",
          expiry: "29 Feb '24",
          change: "-17.55 (39.31%)",
          call_put: "Call",
        },
      ]

export default optionsMockData;